"""Abstract base strategy class.

All strategies must subclass BaseStrategy and implement:
- evaluate(): Check if entry conditions are met, return a signal or None
- should_exit(): Check if exit conditions are met for an open position
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date

from app.core.enums import DayBias, InstrumentType, SignalType, StrategyName
from app.indicators.candle_patterns import Candle
from app.indicators.cpr import CPRResult
from app.indicators.global_market import GlobalCues
from app.indicators.intraday_bias import IntradayBias
from app.indicators.open_interest import OIAnalysis
from app.indicators.previous_day import PreviousDayLevels
from app.indicators.vwap import VWAPResult


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_name: StrategyName
    symbol: str
    signal_type: SignalType  # BUY_CE, BUY_PE, BUY_FUT, SELL_FUT
    instrument_type: InstrumentType  # OPTION, FUTURE, EQUITY
    strike_price: float
    expiry_date: date
    entry_price: float  # Option premium or futures price
    stop_loss: float
    target_price: float | None
    confidence: float  # 0-100
    reason: str  # Human-readable explanation
    indicators: dict  # Snapshot of indicator values at signal time
    # Index-level SL/target from market structure (set by strategy, used by option_resolver)
    index_sl: float | None = None
    index_target: float | None = None
    # Set by option_resolver post-processing (options only)
    index_entry_price: float | None = None  # Underlying index price at signal time
    fyers_option_symbol: str | None = None  # Full Fyers symbol, e.g. "NSE:NIFTY26APR24000CE"
    option_resolved: bool = False  # True after option_resolver has enriched this signal
    # Set by futures_resolver post-processing (futures only)
    fyers_futures_symbol: str | None = None  # Full Fyers symbol, e.g. "NSE:TCS26APRFUT"
    futures_resolved: bool = False
    # Set by strategy_runner post-resolution (snapshot of sizing inputs)
    lots: int | None = None
    quantity: int | None = None
    sizing_meta: dict | None = None


@dataclass
class ExitSignal:
    """Signal to exit a position."""
    reason: str
    exit_type: str  # "SL_HIT", "TARGET_HIT", "TIME_EXIT", "INVALIDATION"


@dataclass
class MarketContext:
    """All market data needed for strategy evaluation."""
    symbol: str
    current_price: float
    candles_5m: list[Candle]
    vwap: VWAPResult | None
    previous_day: PreviousDayLevels | None
    cpr: CPRResult | None
    oi_analysis: OIAnalysis | None
    india_vix: float | None
    current_time_ist: str
    # CAN SLIM extensions (None for non-CANSLIM strategies — backward compatible)
    candles_daily: list[Candle] | None = None      # Last 90 days of daily bars
    volume_avg_20d: int | None = None               # 20-day average daily volume
    relative_strength: float | None = None           # RS rating 0-100
    canslim_data: object | None = None               # StockFundamental row if available
    # Global market context (None when Redis cache is cold or task hasn't run yet)
    global_cues: GlobalCues | None = None            # World indices, FX, commodities
    # Composite intraday bias — replaces yesterday-only hard gate (Phase 2)
    intraday_bias: IntradayBias | None = None        # Live bias: score, strength, components
    # Per-strategy parameters from strategy_configs.parameters JSONB (merged with defaults)
    strategy_params: dict | None = None
    # ATR from 5-min candles (Strategy 5 sub-setup SL sizing)
    atr_5m: float | None = None
    # Today's opening price (gap analysis)
    today_open: float | None = None


class BaseStrategy(ABC):
    """Abstract base for all trading strategies."""

    name: StrategyName
    holding_type: str = "INTRADAY"  # Override to "POSITIONAL" for multi-day strategies
    max_lots: int | None = None  # Override in subclass to cap position size

    @abstractmethod
    def evaluate(self, ctx: MarketContext) -> StrategySignal | None:
        """Evaluate market conditions and return a signal if entry conditions are met.

        Returns None if no trade should be taken.
        """
        ...

    async def get_symbols(self) -> list[str] | None:
        """Override for dynamic symbol selection. Default: None (use DB config)."""
        return None

    @abstractmethod
    def should_exit(
        self,
        ctx: MarketContext,
        entry_price: float,
        stop_loss: float,
        target_price: float | None,
    ) -> ExitSignal | None:
        """Check if an open position should be exited.

        Returns ExitSignal if exit conditions are met, None otherwise.
        """
        ...

