"""Abstract base strategy class.

All strategies must subclass BaseStrategy and implement:
- evaluate(): Check if entry conditions are met, return a signal or None
- should_exit(): Check if exit conditions are met for an open position
- get_position_size(): Calculate lots based on capital and risk params
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date

from app.core.enums import DayBias, SignalType, StrategyName
from app.indicators.candle_patterns import Candle
from app.indicators.cpr import CPRResult
from app.indicators.open_interest import OIAnalysis
from app.indicators.previous_day import PreviousDayLevels
from app.indicators.vwap import VWAPResult


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_name: StrategyName
    symbol: str
    signal_type: SignalType  # BUY_CE or BUY_PE
    strike_price: float
    expiry_date: date
    entry_price: float  # Option premium
    stop_loss: float
    target_price: float | None
    confidence: float  # 0-100
    reason: str  # Human-readable explanation
    indicators: dict  # Snapshot of indicator values at signal time


@dataclass
class ExitSignal:
    """Signal to exit a position."""
    reason: str
    exit_type: str  # "SL_HIT", "TARGET_HIT", "TIME_EXIT", "INVALIDATION"


@dataclass
class MarketContext:
    """All market data needed for strategy evaluation."""
    symbol: str
    current_price: float
    candles_5m: list[Candle]
    vwap: VWAPResult | None
    previous_day: PreviousDayLevels | None
    cpr: CPRResult | None
    oi_analysis: OIAnalysis | None
    india_vix: float | None
    current_time_ist: str


class BaseStrategy(ABC):
    """Abstract base for all trading strategies."""

    name: StrategyName

    @abstractmethod
    def evaluate(self, ctx: MarketContext) -> StrategySignal | None:
        """Evaluate market conditions and return a signal if entry conditions are met.

        Returns None if no trade should be taken.
        """
        ...

    @abstractmethod
    def should_exit(
        self,
        ctx: MarketContext,
        entry_price: float,
        stop_loss: float,
        target_price: float | None,
    ) -> ExitSignal | None:
        """Check if an open position should be exited.

        Returns ExitSignal if exit conditions are met, None otherwise.
        """
        ...

    @abstractmethod
    def get_position_size(
        self,
        capital: float,
        risk_per_trade_pct: float,
        entry_price: float,
        stop_loss: float,
        lot_size: int,
        vix_multiplier: float,
    ) -> int:
        """Calculate number of lots to trade.

        Returns number of lots (minimum 1).
        """
        ...
