"""add signal snapshot columns to trades

Revision ID: 14c22917c90b
Revises: d3f1a4ff97ce
Create Date: 2026-05-22 00:29:49.238275
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c22917c90b'
down_revision: Union[str, None] = 'd3f1a4ff97ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signal_confidence', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('trades', sa.Column('signal_ai_action', sa.String(length=30), nullable=True))
    op.add_column('trades', sa.Column('signal_ai_summary', sa.String(length=300), nullable=True))
    op.add_column('trades', sa.Column('signal_instrument_type', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('signal_type', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('signal_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Backfill individual columns from signals
    op.execute(text("""
        UPDATE trades t SET
            signal_confidence = s.confidence,
            signal_ai_action = s.ai_action,
            signal_ai_summary = s.ai_summary,
            signal_instrument_type = s.instrument_type,
            signal_type = s.signal_type
        FROM signals s
        WHERE t.signal_id = s.id AND t.signal_id IS NOT NULL
    """))

    # Backfill JSONB snapshot from signals
    op.execute(text("""
        UPDATE trades t SET signal_snapshot = jsonb_build_object(
            'confidence', s.confidence,
            'reason', s.reason,
            'indicators', s.indicators,
            'ai_summary', s.ai_summary,
            'ai_rationale', s.ai_rationale,
            'ai_adjustment', s.ai_adjustment,
            'ai_action', s.ai_action,
            'generated_at', s.generated_at,
            'sizing_meta', s.sizing_meta,
            'entry_price', s.entry_price,
            'stop_loss', s.stop_loss,
            'target_price', s.target_price,
            'index_entry_price', s.index_entry_price,
            'instrument_type', s.instrument_type,
            'signal_type', s.signal_type,
            'lots', s.lots,
            'quantity', s.quantity
        )
        FROM signals s
        WHERE t.signal_id = s.id AND t.signal_id IS NOT NULL
    """))

    op.create_index(
        'idx_trades_signal_confidence', 'trades', ['signal_confidence'],
        postgresql_where=text("signal_confidence IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_signal_confidence', table_name='trades')
    op.drop_column('trades', 'signal_snapshot')
    op.drop_column('trades', 'signal_type')
    op.drop_column('trades', 'signal_instrument_type')
    op.drop_column('trades', 'signal_ai_summary')
    op.drop_column('trades', 'signal_ai_action')
    op.drop_column('trades', 'signal_confidence')
    # ### end Alembic commands ###
