"""add ondelete SET NULL to yolo_profile_id FKs

Revision ID: 26d31a3470d8
Revises: df2c3dd55291
Create Date: 2026-05-28 04:10:53.428054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d31a3470d8'
down_revision: Union[str, None] = 'df2c3dd55291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_positions_yolo_profile_id', 'positions', type_='foreignkey')
    op.create_foreign_key('fk_positions_yolo_profile_id', 'positions', 'yolo_profiles', ['yolo_profile_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_trades_yolo_profile_id', 'trades', type_='foreignkey')
    op.create_foreign_key('fk_trades_yolo_profile_id', 'trades', 'yolo_profiles', ['yolo_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trades_yolo_profile_id', 'trades', type_='foreignkey')
    op.create_foreign_key('fk_trades_yolo_profile_id', 'trades', 'yolo_profiles', ['yolo_profile_id'], ['id'])
    op.drop_constraint('fk_positions_yolo_profile_id', 'positions', type_='foreignkey')
    op.create_foreign_key('fk_positions_yolo_profile_id', 'positions', 'yolo_profiles', ['yolo_profile_id'], ['id'])
    # ### end Alembic commands ###
