"""add auto_mode to strategy_configs

Revision ID: 32d975c5e56e
Revises: 8d468bc0bee4
Create Date: 2026-04-17 01:03:53.102465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d975c5e56e'
down_revision: Union[str, None] = '8d468bc0bee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_configs', sa.Column('auto_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_configs', 'auto_mode')
    # ### end Alembic commands ###
