"""add canslim fundamental data tables and position_type columns

Revision ID: 35259f29436b
Revises: 32d975c5e56e
Create Date: 2026-04-17 02:10:43.728096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35259f29436b'
down_revision: Union[str, None] = '32d975c5e56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('roe_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fii_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mf_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('promoter_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'quarter_end', name='uq_fundamental_history_symbol_quarter')
    )
    op.create_index('idx_fundamental_history_symbol', 'fundamental_history', ['symbol'], unique=False)
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('yfinance_ticker', sa.String(length=30), nullable=False),
    sa.Column('market_cap_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('latest_qtr_eps_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('latest_qtr_revenue_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eps_accelerating', sa.Boolean(), nullable=True),
    sa.Column('annual_eps_growth_3yr_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roe_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('operating_margin_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('free_float_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('relative_strength_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fii_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fii_change_qoq', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mf_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mf_change_qoq', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('promoter_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('c_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('a_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('n_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('s_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('l_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('i_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('canslim_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_52w_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pct_from_52w_high', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_fo_eligible', sa.Boolean(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_stock_fundamentals_symbol', 'stock_fundamentals', ['symbol'], unique=False)
    op.add_column('positions', sa.Column('position_type', sa.String(length=15), nullable=False))
    op.add_column('signals', sa.Column('fyers_futures_symbol', sa.String(length=60), nullable=True))
    op.add_column('trades', sa.Column('position_type', sa.String(length=15), nullable=False))
    op.alter_column('trades', 'option_type',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'option_type',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=2),
               nullable=False)
    op.drop_column('trades', 'position_type')
    op.drop_column('signals', 'fyers_futures_symbol')
    op.drop_column('positions', 'position_type')
    op.drop_index('idx_stock_fundamentals_symbol', table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    op.drop_index('idx_fundamental_history_symbol', table_name='fundamental_history')
    op.drop_table('fundamental_history')
    # ### end Alembic commands ###
