"""add executable and blocked_reason to signals

Revision ID: 373982ce98a4
Revises: e28ebbb474c4
Create Date: 2026-04-15 20:50:40.965378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373982ce98a4'
down_revision: Union[str, None] = 'e28ebbb474c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('executable', sa.Boolean(), nullable=False))
    op.add_column('signals', sa.Column('blocked_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'blocked_reason')
    op.drop_column('signals', 'executable')
    # ### end Alembic commands ###
