"""add global_market_snapshots table

Revision ID: 3e647bfdf471
Revises: b39cb8e83680
Create Date: 2026-04-24 05:41:14.776494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e647bfdf471'
down_revision: Union[str, None] = 'b39cb8e83680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_market_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dow_futures_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sp500_close_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nasdaq_close_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('crude_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('usdinr_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dxy_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('us_vix', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pre_open_gap_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dow_futures_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sp500_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nasdaq_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nifty_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('crude_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('usdinr_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dxy_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('global_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', name='uq_global_market_snapshot_ts')
    )
    op.create_index('idx_global_market_snapshot_ts', 'global_market_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_global_market_snapshot_ts', table_name='global_market_snapshots')
    op.drop_table('global_market_snapshots')
    # ### end Alembic commands ###
