"""add trading_config table

Revision ID: 3f00a98c6835
Revises: e0f67c55d282
Create Date: 2026-04-24 02:11:21.792389
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f00a98c6835'
down_revision: Union[str, None] = 'e0f67c55d282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Integer(), nullable=False),
    sa.Column('max_daily_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('paper_trading', sa.Boolean(), nullable=False),
    sa.Column('autonomy_level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_trading_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_config')
    # ### end Alembic commands ###
