"""add signal_history table for Case-2 dedup audit trail

Revision ID: 777000d0996a
Revises: d4b791d15765
Create Date: 2026-05-12 01:28:14.082998
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '777000d0996a'
down_revision: Union[str, None] = 'd4b791d15765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executable', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=100), nullable=True),
    sa.Column('index_entry_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lots', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sizing_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.String(length=300), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_adjustment', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('ai_action', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_history_signal_id', 'signal_history', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signal_history_signal_id', table_name='signal_history')
    op.drop_table('signal_history')
    # ### end Alembic commands ###
