"""add option resolver fields: instrument_type, index_entry_price, fyers_option_symbol

Revision ID: 8d468bc0bee4
Revises: 373982ce98a4
Create Date: 2026-04-16 02:33:27.363935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d468bc0bee4'
down_revision: Union[str, None] = '373982ce98a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('fyers_option_symbol', sa.String(length=60), nullable=True))
    op.add_column('signals', sa.Column('instrument_type', sa.String(length=10), nullable=False, server_default='OPTION'))
    op.add_column('signals', sa.Column('index_entry_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('signals', sa.Column('fyers_option_symbol', sa.String(length=60), nullable=True))
    op.add_column('trades', sa.Column('fyers_option_symbol', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'fyers_option_symbol')
    op.drop_column('signals', 'fyers_option_symbol')
    op.drop_column('signals', 'index_entry_price')
    op.drop_column('signals', 'instrument_type')
    op.drop_column('positions', 'fyers_option_symbol')
    # ### end Alembic commands ###
