"""add lots quantity sizing_meta to signals

Revision ID: b39cb8e83680
Revises: 3f00a98c6835
Create Date: 2026-04-24 02:43:35.671575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b39cb8e83680'
down_revision: Union[str, None] = '3f00a98c6835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('lots', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('sizing_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'sizing_meta')
    op.drop_column('signals', 'quantity')
    op.drop_column('signals', 'lots')
    # ### end Alembic commands ###
