"""add symbol_map to strategy_configs

Revision ID: bdf125f158c4
Revises: 35259f29436b
Create Date: 2026-04-17 02:41:00.485945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdf125f158c4'
down_revision: Union[str, None] = '35259f29436b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'strategy_configs',
        sa.Column('symbol_map', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_configs', 'symbol_map')
    # ### end Alembic commands ###
