"""add permanent watchlist tracking columns

Revision ID: d3f1a4ff97ce
Revises: 2d30e4f1db62
Create Date: 2026-05-21 23:22:36.177626
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f1a4ff97ce'
down_revision: Union[str, None] = '2d30e4f1db62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('is_permanent_watchlist', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('trades', sa.Column('is_permanent_watchlist', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('trading_config', sa.Column('shadow_skip_permanent_watchlist', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('trading_config', sa.Column('yolo_skip_permanent_watchlist', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_config', 'yolo_skip_permanent_watchlist')
    op.drop_column('trading_config', 'shadow_skip_permanent_watchlist')
    op.drop_column('trades', 'is_permanent_watchlist')
    op.drop_column('signals', 'is_permanent_watchlist')
    # ### end Alembic commands ###
