"""add market_data_daily table

Revision ID: d4b791d15765
Revises: a4e2f1c83d92
Create Date: 2026-05-01 02:09:05.567341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b791d15765'
down_revision: Union[str, None] = 'a4e2f1c83d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('delivery_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_data_daily_symbol_date')
    )
    op.create_index('idx_market_data_daily_symbol_date', 'market_data_daily', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_data_daily_symbol_date', table_name='market_data_daily')
    op.drop_table('market_data_daily')
    # ### end Alembic commands ###
