"""add ai fields to signals

Revision ID: d79b95128c64
Revises: 3e647bfdf471
Create Date: 2026-04-24 06:51:51.614893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79b95128c64'
down_revision: Union[str, None] = '3e647bfdf471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('ai_summary', sa.String(length=300), nullable=True))
    op.add_column('signals', sa.Column('ai_rationale', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('ai_adjustment', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('signals', sa.Column('ai_action', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'ai_action')
    op.drop_column('signals', 'ai_adjustment')
    op.drop_column('signals', 'ai_rationale')
    op.drop_column('signals', 'ai_summary')
    # ### end Alembic commands ###
