"""add charges_json and net_pnl to trades

Revision ID: d8adab1c6bd4
Revises: 777000d0996a
Create Date: 2026-05-20 16:32:54.650385
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8adab1c6bd4'
down_revision: Union[str, None] = '777000d0996a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('charges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('trades', sa.Column('net_pnl', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'net_pnl')
    op.drop_column('trades', 'charges_json')
    # ### end Alembic commands ###
