"""add research_reports and research_agent_runs tables

Revision ID: e0f67c55d282
Revises: bdf125f158c4
Create Date: 2026-04-20 22:43:54.430446
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0f67c55d282'
down_revision: Union[str, None] = 'bdf125f158c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('agents_completed', sa.Integer(), nullable=False),
    sa.Column('agents_total', sa.Integer(), nullable=False),
    sa.Column('price_at_research', sa.Float(), nullable=True),
    sa.Column('market_cap_cr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_reports_created', 'research_reports', ['created_at'], unique=False)
    op.create_index('idx_research_reports_status', 'research_reports', ['status'], unique=False)
    op.create_index('idx_research_reports_symbol', 'research_reports', ['symbol'], unique=False)
    op.create_table('research_agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('findings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_sources_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_agent_runs_report', 'research_agent_runs', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_research_agent_runs_report', table_name='research_agent_runs')
    op.drop_table('research_agent_runs')
    op.drop_index('idx_research_reports_symbol', table_name='research_reports')
    op.drop_index('idx_research_reports_status', table_name='research_reports')
    op.drop_index('idx_research_reports_created', table_name='research_reports')
    op.drop_table('research_reports')
    # ### end Alembic commands ###
