"""initial schema

Revision ID: e28ebbb474c4
Revises: 
Create Date: 2026-04-15 18:55:32.152885
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e28ebbb474c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('confirmation_status', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_action', 'agent_logs', ['action_type'], unique=False)
    op.create_index('idx_agent_logs_confirmation', 'agent_logs', ['confirmation_status'], unique=False, postgresql_where='requires_confirmation = true')
    op.create_table('daily_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capital_deployed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('strategies_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('india_vix_open', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cpr_type', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date')
    )
    op.create_table('market_data_1m',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_market_data_symbol_time')
    )
    op.create_index('idx_market_data_symbol_time', 'market_data_1m', ['symbol', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('oi_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('open_interest', sa.BigInteger(), nullable=False),
    sa.Column('oi_change', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'expiry_date', 'strike_price', 'option_type', 'timestamp', name='uq_oi_snapshot')
    )
    op.create_index('idx_oi_snapshots_lookup', 'oi_snapshots', ['symbol', 'expiry_date', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index('idx_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_trade_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_generated_at', 'signals', ['generated_at'], unique=False)
    op.create_index('idx_signals_status', 'signals', ['status'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_name')
    )
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broker_order_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_entry_time', 'trades', ['entry_time'], unique=False)
    op.create_index('idx_trades_status', 'trades', ['status'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_status', table_name='trades')
    op.drop_index('idx_trades_entry_time', table_name='trades')
    op.drop_table('trades')
    op.drop_table('strategy_configs')
    op.drop_index('idx_signals_status', table_name='signals')
    op.drop_index('idx_signals_generated_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_positions_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_oi_snapshots_lookup', table_name='oi_snapshots')
    op.drop_table('oi_snapshots')
    op.drop_index('idx_market_data_symbol_time', table_name='market_data_1m')
    op.drop_table('market_data_1m')
    op.drop_table('daily_summaries')
    op.drop_index('idx_agent_logs_confirmation', table_name='agent_logs', postgresql_where='requires_confirmation = true')
    op.drop_index('idx_agent_logs_action', table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
